sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '4'
  - stable
after_success: >-
  travis-after-all && npm run semantic-release && npm run pages -- --repo
  https://${GH_TOKEN}@github.com/economist-components/component-palette.git
before_install:
  - npm i -g npm
